### ISSUE TITLE
emotibit_heartpy function instructions

### ISSUE THREAD

**Issue by PsychedRR** [dcr-eyethink/eyethinkphysiosync#1]
Hello dcr_eyethink! Could you please update the guidance document with regard to the heartpy functions? it says See the manual entry for emotitbit_heartpy for [installation instructions](https://dcr-eyethink.github.io/eyethinkphysiosync/reference/emotitbit_heartpy.html). But I don't think that link is going anywhere. Thanks!

**Comment by dcr-eyethink** [comment]
ok fixed! I had spelt it emotitbit instead of emotibit in the URL.....
