### ISSUE TITLE
emotibit_session_folders function warnings

### ISSUE THREAD

**Issue by PsychedRR** [dcr-eyethink/eyethinkphysiosync#2]
Hello dcr_eyethink! It seems the emotibit_session_folders function constantly reports warnings e.g., Warning: problem copying .\2024-03-06_13-15-35-874010.csv to .\problem data\2024-03-06_13-15-35-874010.csv: No such file or directory.

I am coding in a windows environment, might be due to how the directory paths are different in different OS(s)?

**Comment by dcr-eyethink** [comment]
OK I think that I have fixed the error! I had made a mess of the filenames, but works now, at least on my system
